version: '3.9'

services:
  dockick_composed:
    tty: true
    container_name: "dockick_composed_container"
    image: ${DOCKER_REGISTRY}dockick_composed
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=htts-password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_HTTPS_PORT=5000
    volumes:
    - ~/.aspnet/https:/https:ro
    links:
      - "mymssqlserver"
    restart: always    
    networks:
      - doc-kick

networks:
  doc-kick:
    external: true