version: '3.9'

services:
  dockick_authentication:
    tty: true
    container_name: "dockick_authentication_container"
    image: ${DOCKER_REGISTRY}dockick_authentication
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:5000;http://+:5003
      - ASPNETCORE_Kestrel__Certificates__Default__Password=htts-password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_HTTPS_PORT=5000
    volumes:
    - ~/.aspnet/https:/https:ro
    restart: always    
    networks:
      - doc-kick

networks:
  doc-kick:
    external: true